build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: true

processors:
  active: true

console-reports:
  active: true

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false

complexity:
  active: true
  CyclomaticComplexMethod:
    threshold: 15
  LongMethod:
    threshold: 60
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

empty-blocks:
  active: true

exceptions:
  active: true
  SwallowedException:
    active: false

naming:
  active: true
  FunctionNaming:
    ignoreAnnotated:
      - Composable
  MatchingDeclarationName:
    active: false

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MaxLineLength:
    active: false
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: true
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
  WildcardImport:
    active: false
