#!/usr/bin/env ruby
require "yaml"
require "fileutils"
require "cgi"

ROOT_DIR = File.expand_path("..", __dir__)
SOURCE_FILE = File.join(ROOT_DIR, "localization", "strings.yml")

ANDROID_LOCALE_DIRS = {
  "en" => "values",
  "es" => "values-es",
  "fr" => "values-fr",
  "de" => "values-de",
  "tr" => "values-tr"
}.freeze

IOS_LPROJ_DIRS = {
  "en" => "en.lproj",
  "es" => "es.lproj",
  "fr" => "fr.lproj",
  "de" => "de.lproj",
  "tr" => "tr.lproj"
}.freeze

def usage!
  abort("usage: #{$PROGRAM_NAME} [--check]")
end

def xml_escape(text)
  text.to_s
    .gsub("&", "&amp;")
    .gsub("<", "&lt;")
    .gsub(">", "&gt;")
    .gsub('"', "&quot;")
    .gsub("'", "\\'")
end

def swift_escape(text)
  text
    .gsub("\\", "\\\\")
    .gsub("\"", "\\\"")
end

def kotlin_escape(text)
  text
    .gsub("\\", "\\\\")
    .gsub("\"", "\\\"")
end

def android_placeholder(text)
  text.gsub(/%\{(\d+)\}/, '%\1$s')
end

def ios_placeholder(text)
  text.gsub(/%\{(\d+)\}/, '%\1$@')
end

def parse_placeholder_indexes(value)
  value.to_s.scan(/%\{(\d+)\}/).flatten.map(&:to_i).sort
end

def flatten_entry_shape(entry)
  case entry
  when String
    [:text]
  when Hash
    [:plural, entry.keys.map(&:to_s).sort]
  else
    [:unknown]
  end
end

def ensure_parity!(base_locale, locales)
  base_entries = locales.fetch(base_locale)
  base_keys = base_entries.keys.sort

  locales.each do |locale, entries|
    missing_keys = base_keys - entries.keys
    extra_keys = entries.keys - base_keys
    abort("Locale '#{locale}' is missing keys: #{missing_keys.join(', ')}") unless missing_keys.empty?
    abort("Locale '#{locale}' has extra keys: #{extra_keys.join(', ')}") unless extra_keys.empty?

    base_keys.each do |key|
      base_entry = base_entries.fetch(key)
      locale_entry = entries.fetch(key)
      if flatten_entry_shape(base_entry) != flatten_entry_shape(locale_entry)
        abort("Locale '#{locale}' key '#{key}' does not match base entry shape")
      end

      case base_entry
      when String
        base_placeholders = parse_placeholder_indexes(base_entry)
        locale_placeholders = parse_placeholder_indexes(locale_entry)
        if base_placeholders != locale_placeholders
          abort("Locale '#{locale}' key '#{key}' has placeholder mismatch")
        end
      when Hash
        base_entry.each_key do |plural_form|
          base_placeholders = parse_placeholder_indexes(base_entry.fetch(plural_form))
          locale_placeholders = parse_placeholder_indexes(locale_entry.fetch(plural_form))
          if base_placeholders != locale_placeholders
            abort("Locale '#{locale}' key '#{key}.#{plural_form}' has placeholder mismatch")
          end
        end
      end
    end
  end
end

def android_name(key)
  key.tr(".", "_")
end

def render_android_xml(locale, entries)
  lines = []
  lines << "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
  lines << "<!-- Generated by scripts/generate-localizations.rb. Do not edit manually. -->"
  lines << "<resources>"
  entries.sort.each do |key, entry|
    resource_name = android_name(key)
    case entry
    when String
      lines << "    <string name=\"#{resource_name}\">#{xml_escape(android_placeholder(entry))}</string>"
    when Hash
      lines << "    <plurals name=\"#{resource_name}\">"
      lines << "        <item quantity=\"one\">#{xml_escape(android_placeholder(entry.fetch('one')))}</item>"
      lines << "        <item quantity=\"other\">#{xml_escape(android_placeholder(entry.fetch('other')))}</item>"
      lines << "    </plurals>"
    end
  end
  lines << "</resources>"
  lines.join("\n") + "\n"
end

def render_ios_strings(locale, entries)
  lines = []
  lines << "/* Generated by scripts/generate-localizations.rb. Do not edit manually. */"
  entries.sort.each do |key, entry|
    case entry
    when String
      lines << "\"#{swift_escape(key)}\" = \"#{swift_escape(ios_placeholder(entry))}\";"
    when Hash
      lines << "\"#{swift_escape(key)}.one\" = \"#{swift_escape(ios_placeholder(entry.fetch('one')))}\";"
      lines << "\"#{swift_escape(key)}.other\" = \"#{swift_escape(ios_placeholder(entry.fetch('other')))}\";"
    end
  end
  lines.join("\n") + "\n"
end

def render_kotlin_catalog(base_locale, locales)
  lines = []
  lines << "package app.debridhub.shared.localization"
  lines << ""
  lines << "internal object GeneratedLocalizationCatalog {"
  lines << "    const val baseLocale: String = \"#{kotlin_escape(base_locale)}\""
  lines << ""
  lines << "    val entries: Map<String, Map<String, LocalizationEntry>> = mapOf("
  locales.each_with_index do |(locale, entries), locale_index|
    locale_suffix = locale_index == locales.size - 1 ? "" : ","
    lines << "        \"#{kotlin_escape(locale)}\" to mapOf("
    entries.sort.each_with_index do |(key, entry), index|
      suffix = index == entries.size - 1 ? "" : ","
      if entry.is_a?(String)
        lines << "            \"#{kotlin_escape(key)}\" to LocalizationEntry.Text(\"#{kotlin_escape(entry)}\")#{suffix}"
      else
        lines << "            \"#{kotlin_escape(key)}\" to LocalizationEntry.Plural("
        lines << "                one = \"#{kotlin_escape(entry.fetch('one'))}\","
        lines << "                other = \"#{kotlin_escape(entry.fetch('other'))}\""
        lines << "            )#{suffix}"
      end
    end
    lines << "        )#{locale_suffix}"
  end
  lines << "    )"
  lines << "}"
  lines.join("\n") + "\n"
end

def render_swift_catalog(base_locale, locales)
  lines = []
  lines << "import Foundation"
  lines << ""
  lines << "private enum LocalizationEntry {"
  lines << "    case text(String)"
  lines << "    case plural(one: String, other: String)"
  lines << "}"
  lines << ""
  lines << "enum AppL10n {"
  lines << "    private static let baseLocale = \"#{swift_escape(base_locale)}\""
  lines << "    static var overrideLanguageTags: [String]?"
  lines << ""
  lines << "    private static let entries: [String: [String: LocalizationEntry]] = ["
  locales.each_with_index do |(locale, entries), locale_index|
    locale_suffix = locale_index == locales.size - 1 ? "" : ","
    lines << "        \"#{swift_escape(locale)}\": ["
    entries.sort.each_with_index do |(key, entry), index|
      suffix = index == entries.size - 1 ? "" : ","
      if entry.is_a?(String)
        lines << "            \"#{swift_escape(key)}\": .text(\"#{swift_escape(entry)}\")#{suffix}"
      else
        lines << "            \"#{swift_escape(key)}\": .plural(one: \"#{swift_escape(entry.fetch('one'))}\", other: \"#{swift_escape(entry.fetch('other'))}\")#{suffix}"
      end
    end
    lines << "        ]#{locale_suffix}"
  end
  lines << "    ]"
  lines << ""
  lines << "    static func text(_ key: String, _ args: String...) -> String {"
  lines << "        resolve(key: key, args: args, count: nil)"
  lines << "    }"
  lines << ""
  lines << "    static func plural(_ key: String, count: Int, _ args: String...) -> String {"
  lines << "        let resolvedArgs = args.isEmpty ? [String(count)] : args"
  lines << "        return resolve(key: key, args: resolvedArgs, count: count)"
  lines << "    }"
  lines << ""
  lines << "    private static func resolve(key: String, args: [String], count: Int?) -> String {"
  lines << "        let localeChain = buildLocaleFallbackChain()"
  lines << "        let entry = localeChain.lazy.compactMap { entries[$0]?[key] }.first"
  lines << "        guard let entry else {"
  lines << "            return key"
  lines << "        }"
  lines << ""
  lines << "        let template: String"
  lines << "        switch entry {"
  lines << "        case let .text(value):"
  lines << "            template = value"
  lines << "        case let .plural(one, other):"
  lines << "            let language = localeChain.first?.components(separatedBy: \"-\").first?.lowercased() ?? baseLocale"
  lines << "            let resolvedCount = count ?? 0"
  lines << "            let useOne = language == \"fr\" ? (resolvedCount == 0 || resolvedCount == 1) : resolvedCount == 1"
  lines << "            template = useOne ? one : other"
  lines << "        }"
  lines << ""
  lines << "        return applyArguments(template, args: args)"
  lines << "    }"
  lines << ""
  lines << "    private static func buildLocaleFallbackChain() -> [String] {"
  lines << "        var resolved: [String] = []"
  lines << "        var seen = Set<String>()"
  lines << "        for languageTag in (overrideLanguageTags ?? Locale.preferredLanguages) {"
  lines << "            if seen.insert(languageTag).inserted { resolved.append(languageTag) }"
  lines << "            let baseLanguage = languageTag.components(separatedBy: \"-\").first ?? languageTag"
  lines << "            if seen.insert(baseLanguage).inserted { resolved.append(baseLanguage) }"
  lines << "        }"
  lines << "        if seen.insert(baseLocale).inserted { resolved.append(baseLocale) }"
  lines << "        return resolved"
  lines << "    }"
  lines << ""
  lines << "    private static func applyArguments(_ template: String, args: [String]) -> String {"
  lines << "        args.enumerated().reduce(template) { partialResult, element in"
  lines << "            partialResult.replacingOccurrences(of: \"%{\\(element.offset + 1)}\", with: element.element)"
  lines << "        }"
  lines << "    }"
  lines << "}"
  lines.join("\n") + "\n"
end

check_mode = false
ARGV.each do |argument|
  case argument
  when "--check"
    check_mode = true
  else
    usage!
  end
end

catalog = YAML.load_file(SOURCE_FILE)
base_locale = catalog.fetch("base_locale")
locales = catalog.fetch("locales")

ensure_parity!(base_locale, locales)

outputs = {}
ANDROID_LOCALE_DIRS.each do |locale, directory|
  entries = locales.fetch(locale)
  outputs[File.join(ROOT_DIR, "androidApp", "src", "main", "res", directory, "strings.xml")] = render_android_xml(locale, entries)
end

IOS_LPROJ_DIRS.each do |locale, directory|
  entries = locales.fetch(locale)
  outputs[File.join(ROOT_DIR, "iosApp", "DebridHubHost", "Resources", directory, "Localizable.strings")] = render_ios_strings(locale, entries)
end

outputs[File.join(ROOT_DIR, "shared", "src", "commonMain", "kotlin", "app", "debridhub", "shared", "localization", "GeneratedLocalizationCatalog.kt")] = render_kotlin_catalog(base_locale, locales)
outputs[File.join(ROOT_DIR, "iosApp", "DebridHubHost", "Generated", "AppL10n.generated.swift")] = render_swift_catalog(base_locale, locales)

if check_mode
  stale_outputs = outputs.select do |path, content|
    !File.file?(path) || File.read(path) != content
  end
  unless stale_outputs.empty?
    abort("Localization outputs are stale. Re-run scripts/generate-localizations.rb\n#{stale_outputs.keys.join("\n")}")
  end
  puts "Localization outputs are up to date."
else
  outputs.each do |path, content|
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, content)
  end
  puts "Generated #{outputs.size} localization output files."
end
