package app.debridhub.shared.localization

internal object GeneratedLocalizationCatalog {
    const val baseLocale: String = "en"

    val entries: Map<String, Map<String, LocalizationEntry>> = mapOf(
        "en" to mapOf(
            "account.days_remaining" to LocalizationEntry.Text("Days remaining: %{1}"),
            "account.expires" to LocalizationEntry.Text("Expires: %{1}"),
            "account.expiry_state.active" to LocalizationEntry.Text("Active"),
            "account.expiry_state.expired" to LocalizationEntry.Text("Expired"),
            "account.expiry_state.expiring_soon" to LocalizationEntry.Text("Expiring soon"),
            "account.expiry_state.unknown" to LocalizationEntry.Text("Unknown"),
            "account.last_checked" to LocalizationEntry.Text("Last checked: %{1}"),
            "account.no_data" to LocalizationEntry.Text("No account data loaded yet."),
            "account.premium" to LocalizationEntry.Text("Premium: %{1}"),
            "account.section_title" to LocalizationEntry.Text("Account Status"),
            "account.state" to LocalizationEntry.Text("State: %{1}"),
            "account.username" to LocalizationEntry.Text("Username: %{1}"),
            "common.actions" to LocalizationEntry.Text("Actions"),
            "common.active" to LocalizationEntry.Text("Active"),
            "common.app_name" to LocalizationEntry.Text("DebridHub"),
            "common.back" to LocalizationEntry.Text("Back"),
            "common.cancel_authorization" to LocalizationEntry.Text("Cancel Authorization"),
            "common.connect_real_debrid" to LocalizationEntry.Text("Connect Real-Debrid"),
            "common.copy_code" to LocalizationEntry.Text("Copy Code"),
            "common.disconnect" to LocalizationEntry.Text("Disconnect"),
            "common.enable_notifications" to LocalizationEntry.Text("Enable Notifications"),
            "common.enabling_notifications" to LocalizationEntry.Text("Enabling Notifications..."),
            "common.export_json" to LocalizationEntry.Text("Export JSON"),
            "common.exporting" to LocalizationEntry.Text("Exporting..."),
            "common.inactive" to LocalizationEntry.Text("Inactive"),
            "common.loading" to LocalizationEntry.Text("Loading..."),
            "common.no_browser_available" to LocalizationEntry.Text("No browser available to open Real-Debrid."),
            "common.none" to LocalizationEntry.Text("None"),
            "common.notifications" to LocalizationEntry.Text("Notifications"),
            "common.open_authorization_page" to LocalizationEntry.Text("Open Authorization Page"),
            "common.open_notification_settings" to LocalizationEntry.Text("Open Notification Settings"),
            "common.refresh_preview" to LocalizationEntry.Text("Refresh Preview"),
            "common.refresh_status" to LocalizationEntry.Text("Refresh Status"),
            "common.refreshing_status" to LocalizationEntry.Text("Refreshing..."),
            "common.share_diagnostics" to LocalizationEntry.Text("Share diagnostics"),
            "common.start_again" to LocalizationEntry.Text("Start Again"),
            "common.starting" to LocalizationEntry.Text("Starting..."),
            "common.trust_center" to LocalizationEntry.Text("Trust Center"),
            "common.unable_open_notification_settings" to LocalizationEntry.Text("Unable to open notification settings."),
            "common.unknown" to LocalizationEntry.Text("Unknown"),
            "errors.authorization_failed" to LocalizationEntry.Text("Authorization failed."),
            "errors.network_unreachable" to LocalizationEntry.Text("Couldn't reach Real-Debrid. Check your internet connection or try a different network."),
            "errors.secure_connection_failed" to LocalizationEntry.Text("Secure connection to Real-Debrid failed. Your network appears to be intercepting or downgrading HTTPS traffic to api.real-debrid.com. Disable captive portals, VPNs, secure web gateways, or TLS inspection, or try a different network."),
            "messages.authorization_completed" to LocalizationEntry.Text("Authorization completed."),
            "messages.authorization_denied" to LocalizationEntry.Text("Real-Debrid denied the authorization request."),
            "messages.authorization_expired" to LocalizationEntry.Text("The device authorization session expired. Start again."),
            "messages.authorization_unexpected" to LocalizationEntry.Text("Unexpected authorization state."),
            "messages.diagnostics_exported" to LocalizationEntry.Text("Diagnostics exported to %{1}"),
            "messages.disconnected" to LocalizationEntry.Text("Disconnected from Real-Debrid."),
            "messages.notifications_enabled" to LocalizationEntry.Text("Notifications enabled."),
            "messages.notifications_still_disabled" to LocalizationEntry.Text("Notifications remain disabled. Open system settings if you want reminder alerts."),
            "messages.unable_export_diagnostics" to LocalizationEntry.Text("Unable to export diagnostics."),
            "messages.unable_load_diagnostics_preview" to LocalizationEntry.Text("Unable to load diagnostics preview."),
            "messages.unable_refresh_account" to LocalizationEntry.Text("Unable to refresh account status."),
            "messages.unable_start_authorization" to LocalizationEntry.Text("Unable to start authorization."),
            "onboarding.before_connect_step_1" to LocalizationEntry.Text("1. Tap Connect Real-Debrid to request a device code."),
            "onboarding.before_connect_step_2" to LocalizationEntry.Text("2. Copy the code if you want, then approve the device on Real-Debrid."),
            "onboarding.before_connect_step_3" to LocalizationEntry.Text("3. If your browser handoff is interrupted, use Open Authorization Page below."),
            "onboarding.before_connect_step_4" to LocalizationEntry.Text("4. Return here while DebridHub polls for completion."),
            "onboarding.before_connect_step_5" to LocalizationEntry.Text("You can open Trust Center first if you want to inspect privacy, security, diagnostics, and compliance details."),
            "onboarding.before_connect_title" to LocalizationEntry.Text("Before you connect"),
            "onboarding.direct_verification_url" to LocalizationEntry.Text("Direct verification URL: %{1}"),
            "onboarding.enter_code" to LocalizationEntry.Text("Enter this code on Real-Debrid."),
            "onboarding.finish_authorization_title" to LocalizationEntry.Text("Finish authorization"),
            "onboarding.hero_body" to LocalizationEntry.Text("DebridHub talks directly to the official Real-Debrid API. Tokens stay on device and no backend is involved."),
            "onboarding.hero_title" to LocalizationEntry.Text("Track your Real-Debrid subscription and renew before it lapses."),
            "onboarding.notifications_already_enabled" to LocalizationEntry.Text("Notifications are already enabled on this device."),
            "onboarding.notifications_disabled_help" to LocalizationEntry.Text("Notifications are currently disabled for DebridHub. You can try the permission prompt again or re-enable alerts from system settings."),
            "onboarding.notifications_later" to LocalizationEntry.Text("You can enable notifications now or later. Reminder alerts start once your account is connected."),
            "onboarding.polling_until" to LocalizationEntry.Text("Polling every %{1}s until %{2}"),
            "onboarding.verification_url" to LocalizationEntry.Text("Verification URL: %{1}"),
            "onboarding.waiting_for_approval" to LocalizationEntry.Text("Waiting for Real-Debrid approval. After you approve the device, come back here and DebridHub will finish the login automatically."),
            "reminders.day_count" to LocalizationEntry.Plural(
                one = "%{1} day",
                other = "%{1} days"
            ),
            "reminders.days_before_expiry" to LocalizationEntry.Text("Days before expiry"),
            "reminders.enable" to LocalizationEntry.Text("Enable reminders"),
            "reminders.local_schedule_intro" to LocalizationEntry.Text("DebridHub will schedule these local notifications on this device:"),
            "reminders.no_future_planned" to LocalizationEntry.Text("No future reminders are planned right now. This can happen if the expiry date is very close, already passed, or your selected reminder windows are already in the past."),
            "reminders.notification.expired_yesterday" to LocalizationEntry.Text("Your Real-Debrid subscription expired yesterday"),
            "reminders.notification.expires_in" to LocalizationEntry.Plural(
                one = "Your Real-Debrid subscription expires in %{1} day",
                other = "Your Real-Debrid subscription expires in %{1} days"
            ),
            "reminders.notification.expires_today" to LocalizationEntry.Text("Your Real-Debrid subscription expires today"),
            "reminders.notifications_disabled" to LocalizationEntry.Text("Reminders are planned, but notifications are currently disabled for DebridHub. Re-enable them in system settings if you want these alerts to fire."),
            "reminders.notify_after_expiry" to LocalizationEntry.Text("Notify after expiry"),
            "reminders.notify_on_expiry" to LocalizationEntry.Text("Notify on expiry day"),
            "reminders.planned_times" to LocalizationEntry.Text("Planned reminder times:"),
            "reminders.refresh_to_preview" to LocalizationEntry.Text("Refresh your account to preview local reminders."),
            "reminders.schedule_title" to LocalizationEntry.Text("Expected Reminder Schedule"),
            "reminders.scheduled_item" to LocalizationEntry.Text("%{1}: %{2}"),
            "reminders.selected" to LocalizationEntry.Text("Selected: %{1}"),
            "reminders.settings_title" to LocalizationEntry.Text("Reminder Settings"),
            "reminders.turned_off" to LocalizationEntry.Text("Reminders are currently turned off."),
            "trust_center.about_line_1" to LocalizationEntry.Text("Current scope is intentionally narrow: account auth, account-status reads, local reminder scheduling, and local diagnostics export."),
            "trust_center.about_line_2" to LocalizationEntry.Text("The app does not currently implement unrestrict, downloads, torrent management, streaming, generated-link sharing, or multi-user account management."),
            "trust_center.about_line_3" to LocalizationEntry.Text("DebridHub uses official Real-Debrid API endpoints and the documented device-auth flow. Users are still responsible for following Real-Debrid's own Terms and account rules."),
            "trust_center.about_title" to LocalizationEntry.Text("About & Compliance"),
            "trust_center.diagnostics_line_1" to LocalizationEntry.Text("Diagnostics export currently includes app version, OS version, last sync timestamp, account expiry state, and limited non-sensitive runtime flags."),
            "trust_center.diagnostics_line_2" to LocalizationEntry.Text("Diagnostics export excludes access tokens, refresh tokens, client secrets, username, email, and full account history."),
            "trust_center.diagnostics_title" to LocalizationEntry.Text("Diagnostics"),
            "trust_center.hero_body" to LocalizationEntry.Text("This is in-app product copy based on the current implementation, not a marketing layer or webview."),
            "trust_center.hero_title" to LocalizationEntry.Text("See exactly how DebridHub handles auth, storage, diagnostics, and feature boundaries."),
            "trust_center.preview_unavailable" to LocalizationEntry.Text("Diagnostics preview is not available yet."),
            "trust_center.privacy_line_1" to LocalizationEntry.Text("DebridHub has no backend. The app talks directly to Real-Debrid from your device."),
            "trust_center.privacy_line_2" to LocalizationEntry.Text("There is no analytics SDK, tracking pixel, crash-reporting service, or remote account sync in the current app."),
            "trust_center.privacy_line_3" to LocalizationEntry.Text("Reminder notifications are local to this device and are scheduled using your locally stored account status."),
            "trust_center.privacy_line_4" to LocalizationEntry.Text("Diagnostics export is manual. Nothing is sent anywhere unless you explicitly share the exported file yourself."),
            "trust_center.privacy_title" to LocalizationEntry.Text("Privacy"),
            "trust_center.security_line_1" to LocalizationEntry.Text("Authentication uses Real-Debrid's official OAuth2 device flow rather than password collection."),
            "trust_center.security_line_2_android" to LocalizationEntry.Text("Android stores auth state with EncryptedSharedPreferences."),
            "trust_center.security_line_2_ios" to LocalizationEntry.Text("iOS stores auth state in Keychain and migrates legacy NSUserDefaults auth state on first read."),
            "trust_center.security_line_3" to LocalizationEntry.Text("Disconnect clears saved auth state and cancels reminders. DebridHub does not need a companion server to function."),
            "trust_center.security_title" to LocalizationEntry.Text("Security")
        ),
        "es" to mapOf(
            "account.days_remaining" to LocalizationEntry.Text("Días restantes: %{1}"),
            "account.expires" to LocalizationEntry.Text("Caduca: %{1}"),
            "account.expiry_state.active" to LocalizationEntry.Text("Activa"),
            "account.expiry_state.expired" to LocalizationEntry.Text("Caducada"),
            "account.expiry_state.expiring_soon" to LocalizationEntry.Text("Próxima a caducar"),
            "account.expiry_state.unknown" to LocalizationEntry.Text("Desconocido"),
            "account.last_checked" to LocalizationEntry.Text("Última comprobación: %{1}"),
            "account.no_data" to LocalizationEntry.Text("Todavía no se han cargado datos de la cuenta."),
            "account.premium" to LocalizationEntry.Text("Premium: %{1}"),
            "account.section_title" to LocalizationEntry.Text("Estado de la cuenta"),
            "account.state" to LocalizationEntry.Text("Estado: %{1}"),
            "account.username" to LocalizationEntry.Text("Usuario: %{1}"),
            "common.actions" to LocalizationEntry.Text("Acciones"),
            "common.active" to LocalizationEntry.Text("Activo"),
            "common.app_name" to LocalizationEntry.Text("DebridHub"),
            "common.back" to LocalizationEntry.Text("Atrás"),
            "common.cancel_authorization" to LocalizationEntry.Text("Cancelar autorización"),
            "common.connect_real_debrid" to LocalizationEntry.Text("Conectar Real-Debrid"),
            "common.copy_code" to LocalizationEntry.Text("Copiar código"),
            "common.disconnect" to LocalizationEntry.Text("Desconectar"),
            "common.enable_notifications" to LocalizationEntry.Text("Activar notificaciones"),
            "common.enabling_notifications" to LocalizationEntry.Text("Activando notificaciones..."),
            "common.export_json" to LocalizationEntry.Text("Exportar JSON"),
            "common.exporting" to LocalizationEntry.Text("Exportando..."),
            "common.inactive" to LocalizationEntry.Text("Inactivo"),
            "common.loading" to LocalizationEntry.Text("Cargando..."),
            "common.no_browser_available" to LocalizationEntry.Text("No hay ningún navegador disponible para abrir Real-Debrid."),
            "common.none" to LocalizationEntry.Text("Ninguno"),
            "common.notifications" to LocalizationEntry.Text("Notificaciones"),
            "common.open_authorization_page" to LocalizationEntry.Text("Abrir página de autorización"),
            "common.open_notification_settings" to LocalizationEntry.Text("Abrir ajustes de notificaciones"),
            "common.refresh_preview" to LocalizationEntry.Text("Actualizar vista previa"),
            "common.refresh_status" to LocalizationEntry.Text("Actualizar estado"),
            "common.refreshing_status" to LocalizationEntry.Text("Actualizando..."),
            "common.share_diagnostics" to LocalizationEntry.Text("Compartir diagnóstico"),
            "common.start_again" to LocalizationEntry.Text("Volver a empezar"),
            "common.starting" to LocalizationEntry.Text("Iniciando..."),
            "common.trust_center" to LocalizationEntry.Text("Centro de confianza"),
            "common.unable_open_notification_settings" to LocalizationEntry.Text("No se pudieron abrir los ajustes de notificaciones."),
            "common.unknown" to LocalizationEntry.Text("Desconocido"),
            "errors.authorization_failed" to LocalizationEntry.Text("La autorización falló."),
            "errors.network_unreachable" to LocalizationEntry.Text("No se pudo acceder a Real-Debrid. Comprueba tu conexión a Internet o prueba otra red."),
            "errors.secure_connection_failed" to LocalizationEntry.Text("La conexión segura con Real-Debrid falló. Tu red parece estar interceptando o degradando el tráfico HTTPS hacia api.real-debrid.com. Desactiva portales cautivos, VPN, pasarelas web seguras o inspección TLS, o prueba otra red."),
            "messages.authorization_completed" to LocalizationEntry.Text("Autorización completada."),
            "messages.authorization_denied" to LocalizationEntry.Text("Real-Debrid rechazó la solicitud de autorización."),
            "messages.authorization_expired" to LocalizationEntry.Text("La sesión de autorización del dispositivo caducó. Vuelve a empezar."),
            "messages.authorization_unexpected" to LocalizationEntry.Text("Estado de autorización inesperado."),
            "messages.diagnostics_exported" to LocalizationEntry.Text("Diagnósticos exportados a %{1}"),
            "messages.disconnected" to LocalizationEntry.Text("Desconectado de Real-Debrid."),
            "messages.notifications_enabled" to LocalizationEntry.Text("Notificaciones activadas."),
            "messages.notifications_still_disabled" to LocalizationEntry.Text("Las notificaciones siguen desactivadas. Abre los ajustes del sistema si quieres recibir alertas de recordatorio."),
            "messages.unable_export_diagnostics" to LocalizationEntry.Text("No se pudieron exportar los diagnósticos."),
            "messages.unable_load_diagnostics_preview" to LocalizationEntry.Text("No se pudo cargar la vista previa de diagnósticos."),
            "messages.unable_refresh_account" to LocalizationEntry.Text("No se pudo actualizar el estado de la cuenta."),
            "messages.unable_start_authorization" to LocalizationEntry.Text("No se pudo iniciar la autorización."),
            "onboarding.before_connect_step_1" to LocalizationEntry.Text("1. Toca Conectar Real-Debrid para solicitar un código de dispositivo."),
            "onboarding.before_connect_step_2" to LocalizationEntry.Text("2. Copia el código si quieres y luego aprueba el dispositivo en Real-Debrid."),
            "onboarding.before_connect_step_3" to LocalizationEntry.Text("3. Si la apertura del navegador se interrumpe, usa Abrir página de autorización más abajo."),
            "onboarding.before_connect_step_4" to LocalizationEntry.Text("4. Vuelve aquí mientras DebridHub espera la confirmación."),
            "onboarding.before_connect_step_5" to LocalizationEntry.Text("Puedes abrir primero el Centro de confianza si quieres revisar la privacidad, la seguridad, los diagnósticos y los detalles de cumplimiento."),
            "onboarding.before_connect_title" to LocalizationEntry.Text("Antes de conectarte"),
            "onboarding.direct_verification_url" to LocalizationEntry.Text("URL directa de verificación: %{1}"),
            "onboarding.enter_code" to LocalizationEntry.Text("Introduce este código en Real-Debrid."),
            "onboarding.finish_authorization_title" to LocalizationEntry.Text("Completar autorización"),
            "onboarding.hero_body" to LocalizationEntry.Text("DebridHub se comunica directamente con la API oficial de Real-Debrid. Los tokens permanecen en el dispositivo y no interviene ningún backend."),
            "onboarding.hero_title" to LocalizationEntry.Text("Sigue tu suscripción de Real-Debrid y renuévala antes de que caduque."),
            "onboarding.notifications_already_enabled" to LocalizationEntry.Text("Las notificaciones ya están activadas en este dispositivo."),
            "onboarding.notifications_disabled_help" to LocalizationEntry.Text("Las notificaciones están desactivadas para DebridHub. Puedes volver a intentar el permiso o reactivar las alertas en los ajustes del sistema."),
            "onboarding.notifications_later" to LocalizationEntry.Text("Puedes activar las notificaciones ahora o más tarde. Las alertas de recordatorio comenzarán una vez que tu cuenta esté conectada."),
            "onboarding.polling_until" to LocalizationEntry.Text("Comprobando cada %{1}s hasta %{2}"),
            "onboarding.verification_url" to LocalizationEntry.Text("URL de verificación: %{1}"),
            "onboarding.waiting_for_approval" to LocalizationEntry.Text("Esperando la aprobación de Real-Debrid. Después de aprobar el dispositivo, vuelve aquí y DebridHub completará el inicio de sesión automáticamente."),
            "reminders.day_count" to LocalizationEntry.Plural(
                one = "%{1} día",
                other = "%{1} días"
            ),
            "reminders.days_before_expiry" to LocalizationEntry.Text("Días antes del vencimiento"),
            "reminders.enable" to LocalizationEntry.Text("Activar recordatorios"),
            "reminders.local_schedule_intro" to LocalizationEntry.Text("DebridHub programará estas notificaciones locales en este dispositivo:"),
            "reminders.no_future_planned" to LocalizationEntry.Text("No hay recordatorios futuros planificados en este momento. Puede ocurrir si la fecha de vencimiento está muy cerca, ya pasó o las ventanas elegidas ya quedaron atrás."),
            "reminders.notification.expired_yesterday" to LocalizationEntry.Text("Tu suscripción de Real-Debrid caducó ayer"),
            "reminders.notification.expires_in" to LocalizationEntry.Plural(
                one = "Tu suscripción de Real-Debrid caduca en %{1} día",
                other = "Tu suscripción de Real-Debrid caduca en %{1} días"
            ),
            "reminders.notification.expires_today" to LocalizationEntry.Text("Tu suscripción de Real-Debrid caduca hoy"),
            "reminders.notifications_disabled" to LocalizationEntry.Text("Hay recordatorios planificados, pero las notificaciones están desactivadas para DebridHub. Reactívalas en los ajustes del sistema si quieres que se envíen estas alertas."),
            "reminders.notify_after_expiry" to LocalizationEntry.Text("Notificar después del vencimiento"),
            "reminders.notify_on_expiry" to LocalizationEntry.Text("Notificar el día del vencimiento"),
            "reminders.planned_times" to LocalizationEntry.Text("Horas de recordatorio planificadas:"),
            "reminders.refresh_to_preview" to LocalizationEntry.Text("Actualiza tu cuenta para ver una vista previa de los recordatorios locales."),
            "reminders.schedule_title" to LocalizationEntry.Text("Calendario esperado de recordatorios"),
            "reminders.scheduled_item" to LocalizationEntry.Text("%{1}: %{2}"),
            "reminders.selected" to LocalizationEntry.Text("Seleccionado: %{1}"),
            "reminders.settings_title" to LocalizationEntry.Text("Ajustes de recordatorios"),
            "reminders.turned_off" to LocalizationEntry.Text("Los recordatorios están desactivados actualmente."),
            "trust_center.about_line_1" to LocalizationEntry.Text("El alcance actual es intencionadamente reducido: autenticación de cuenta, lectura del estado de la cuenta, programación local de recordatorios y exportación local de diagnósticos."),
            "trust_center.about_line_2" to LocalizationEntry.Text("La app no implementa actualmente desbloqueo, descargas, gestión de torrents, streaming, uso compartido de enlaces generados ni gestión multiusuario."),
            "trust_center.about_line_3" to LocalizationEntry.Text("DebridHub usa los endpoints oficiales de la API de Real-Debrid y el flujo de autenticación por dispositivo documentado. Los usuarios siguen siendo responsables de cumplir los Términos y las reglas de cuenta de Real-Debrid."),
            "trust_center.about_title" to LocalizationEntry.Text("Acerca de y cumplimiento"),
            "trust_center.diagnostics_line_1" to LocalizationEntry.Text("La exportación de diagnósticos incluye actualmente la versión de la app, la versión del sistema operativo, la última sincronización, el estado de vencimiento de la cuenta y algunas marcas de ejecución no sensibles."),
            "trust_center.diagnostics_line_2" to LocalizationEntry.Text("La exportación de diagnósticos excluye tokens de acceso, tokens de actualización, secretos de cliente, nombre de usuario, correo electrónico e historial completo de la cuenta."),
            "trust_center.diagnostics_title" to LocalizationEntry.Text("Diagnósticos"),
            "trust_center.hero_body" to LocalizationEntry.Text("Este texto del producto dentro de la app se basa en la implementación actual, no en una capa de marketing ni en una vista web."),
            "trust_center.hero_title" to LocalizationEntry.Text("Mira exactamente cómo DebridHub gestiona la autenticación, el almacenamiento, los diagnósticos y los límites de la función."),
            "trust_center.preview_unavailable" to LocalizationEntry.Text("La vista previa de diagnósticos todavía no está disponible."),
            "trust_center.privacy_line_1" to LocalizationEntry.Text("DebridHub no tiene backend. La app se comunica directamente con Real-Debrid desde tu dispositivo."),
            "trust_center.privacy_line_2" to LocalizationEntry.Text("No hay SDK de analítica, píxel de seguimiento, servicio de informes de fallos ni sincronización remota de la cuenta en la app actual."),
            "trust_center.privacy_line_3" to LocalizationEntry.Text("Las notificaciones de recordatorio son locales a este dispositivo y se programan usando el estado de la cuenta almacenado localmente."),
            "trust_center.privacy_line_4" to LocalizationEntry.Text("La exportación de diagnósticos es manual. No se envía nada a ningún sitio a menos que compartas explícitamente el archivo exportado."),
            "trust_center.privacy_title" to LocalizationEntry.Text("Privacidad"),
            "trust_center.security_line_1" to LocalizationEntry.Text("La autenticación usa el flujo oficial OAuth2 Device Flow de Real-Debrid en lugar de pedir tu contraseña."),
            "trust_center.security_line_2_android" to LocalizationEntry.Text("Android almacena el estado de autenticación con EncryptedSharedPreferences."),
            "trust_center.security_line_2_ios" to LocalizationEntry.Text("iOS almacena el estado de autenticación en Keychain y migra el estado heredado de NSUserDefaults en la primera lectura."),
            "trust_center.security_line_3" to LocalizationEntry.Text("Desconectar borra el estado de autenticación guardado y cancela los recordatorios. DebridHub no necesita un servidor complementario para funcionar."),
            "trust_center.security_title" to LocalizationEntry.Text("Seguridad")
        ),
        "fr" to mapOf(
            "account.days_remaining" to LocalizationEntry.Text("Jours restants : %{1}"),
            "account.expires" to LocalizationEntry.Text("Expire le : %{1}"),
            "account.expiry_state.active" to LocalizationEntry.Text("Actif"),
            "account.expiry_state.expired" to LocalizationEntry.Text("Expiré"),
            "account.expiry_state.expiring_soon" to LocalizationEntry.Text("Expire bientôt"),
            "account.expiry_state.unknown" to LocalizationEntry.Text("Inconnu"),
            "account.last_checked" to LocalizationEntry.Text("Dernière vérification : %{1}"),
            "account.no_data" to LocalizationEntry.Text("Aucune donnée de compte n’a encore été chargée."),
            "account.premium" to LocalizationEntry.Text("Premium : %{1}"),
            "account.section_title" to LocalizationEntry.Text("État du compte"),
            "account.state" to LocalizationEntry.Text("État : %{1}"),
            "account.username" to LocalizationEntry.Text("Nom d’utilisateur : %{1}"),
            "common.actions" to LocalizationEntry.Text("Actions"),
            "common.active" to LocalizationEntry.Text("Actif"),
            "common.app_name" to LocalizationEntry.Text("DebridHub"),
            "common.back" to LocalizationEntry.Text("Retour"),
            "common.cancel_authorization" to LocalizationEntry.Text("Annuler l’autorisation"),
            "common.connect_real_debrid" to LocalizationEntry.Text("Connecter Real-Debrid"),
            "common.copy_code" to LocalizationEntry.Text("Copier le code"),
            "common.disconnect" to LocalizationEntry.Text("Déconnecter"),
            "common.enable_notifications" to LocalizationEntry.Text("Activer les notifications"),
            "common.enabling_notifications" to LocalizationEntry.Text("Activation des notifications..."),
            "common.export_json" to LocalizationEntry.Text("Exporter en JSON"),
            "common.exporting" to LocalizationEntry.Text("Exportation..."),
            "common.inactive" to LocalizationEntry.Text("Inactif"),
            "common.loading" to LocalizationEntry.Text("Chargement..."),
            "common.no_browser_available" to LocalizationEntry.Text("Aucun navigateur n’est disponible pour ouvrir Real-Debrid."),
            "common.none" to LocalizationEntry.Text("Aucun"),
            "common.notifications" to LocalizationEntry.Text("Notifications"),
            "common.open_authorization_page" to LocalizationEntry.Text("Ouvrir la page d’autorisation"),
            "common.open_notification_settings" to LocalizationEntry.Text("Ouvrir les réglages de notifications"),
            "common.refresh_preview" to LocalizationEntry.Text("Actualiser l’aperçu"),
            "common.refresh_status" to LocalizationEntry.Text("Actualiser le statut"),
            "common.refreshing_status" to LocalizationEntry.Text("Actualisation..."),
            "common.share_diagnostics" to LocalizationEntry.Text("Partager les diagnostics"),
            "common.start_again" to LocalizationEntry.Text("Recommencer"),
            "common.starting" to LocalizationEntry.Text("Démarrage..."),
            "common.trust_center" to LocalizationEntry.Text("Centre de confiance"),
            "common.unable_open_notification_settings" to LocalizationEntry.Text("Impossible d’ouvrir les réglages de notifications."),
            "common.unknown" to LocalizationEntry.Text("Inconnu"),
            "errors.authorization_failed" to LocalizationEntry.Text("L’autorisation a échoué."),
            "errors.network_unreachable" to LocalizationEntry.Text("Impossible d’atteindre Real-Debrid. Vérifiez votre connexion Internet ou essayez un autre réseau."),
            "errors.secure_connection_failed" to LocalizationEntry.Text("La connexion sécurisée à Real-Debrid a échoué. Votre réseau semble intercepter ou dégrader le trafic HTTPS vers api.real-debrid.com. Désactivez les portails captifs, VPN, passerelles web sécurisées ou l’inspection TLS, ou essayez un autre réseau."),
            "messages.authorization_completed" to LocalizationEntry.Text("Autorisation terminée."),
            "messages.authorization_denied" to LocalizationEntry.Text("Real-Debrid a refusé la demande d’autorisation."),
            "messages.authorization_expired" to LocalizationEntry.Text("La session d’autorisation de l’appareil a expiré. Recommencez."),
            "messages.authorization_unexpected" to LocalizationEntry.Text("État d’autorisation inattendu."),
            "messages.diagnostics_exported" to LocalizationEntry.Text("Diagnostics exportés vers %{1}"),
            "messages.disconnected" to LocalizationEntry.Text("Déconnecté de Real-Debrid."),
            "messages.notifications_enabled" to LocalizationEntry.Text("Notifications activées."),
            "messages.notifications_still_disabled" to LocalizationEntry.Text("Les notifications restent désactivées. Ouvrez les réglages système si vous voulez recevoir des alertes de rappel."),
            "messages.unable_export_diagnostics" to LocalizationEntry.Text("Impossible d’exporter les diagnostics."),
            "messages.unable_load_diagnostics_preview" to LocalizationEntry.Text("Impossible de charger l’aperçu des diagnostics."),
            "messages.unable_refresh_account" to LocalizationEntry.Text("Impossible d’actualiser l’état du compte."),
            "messages.unable_start_authorization" to LocalizationEntry.Text("Impossible de démarrer l’autorisation."),
            "onboarding.before_connect_step_1" to LocalizationEntry.Text("1. Touchez Connecter Real-Debrid pour demander un code d’appareil."),
            "onboarding.before_connect_step_2" to LocalizationEntry.Text("2. Copiez le code si vous le souhaitez, puis approuvez l’appareil sur Real-Debrid."),
            "onboarding.before_connect_step_3" to LocalizationEntry.Text("3. Si l’ouverture du navigateur est interrompue, utilisez Ouvrir la page d’autorisation ci-dessous."),
            "onboarding.before_connect_step_4" to LocalizationEntry.Text("4. Revenez ici pendant que DebridHub attend la confirmation."),
            "onboarding.before_connect_step_5" to LocalizationEntry.Text("Vous pouvez d’abord ouvrir le Centre de confiance si vous souhaitez examiner la confidentialité, la sécurité, les diagnostics et les détails de conformité."),
            "onboarding.before_connect_title" to LocalizationEntry.Text("Avant de vous connecter"),
            "onboarding.direct_verification_url" to LocalizationEntry.Text("URL directe de vérification : %{1}"),
            "onboarding.enter_code" to LocalizationEntry.Text("Saisissez ce code sur Real-Debrid."),
            "onboarding.finish_authorization_title" to LocalizationEntry.Text("Terminer l’autorisation"),
            "onboarding.hero_body" to LocalizationEntry.Text("DebridHub communique directement avec l’API officielle de Real-Debrid. Les jetons restent sur l’appareil et aucun backend n’intervient."),
            "onboarding.hero_title" to LocalizationEntry.Text("Suivez votre abonnement Real-Debrid et renouvelez-le avant son expiration."),
            "onboarding.notifications_already_enabled" to LocalizationEntry.Text("Les notifications sont déjà activées sur cet appareil."),
            "onboarding.notifications_disabled_help" to LocalizationEntry.Text("Les notifications sont actuellement désactivées pour DebridHub. Vous pouvez réessayer la demande d’autorisation ou réactiver les alertes dans les réglages du système."),
            "onboarding.notifications_later" to LocalizationEntry.Text("Vous pouvez activer les notifications maintenant ou plus tard. Les alertes de rappel commenceront une fois votre compte connecté."),
            "onboarding.polling_until" to LocalizationEntry.Text("Vérification toutes les %{1}s jusqu’à %{2}"),
            "onboarding.verification_url" to LocalizationEntry.Text("URL de vérification : %{1}"),
            "onboarding.waiting_for_approval" to LocalizationEntry.Text("En attente de l’approbation de Real-Debrid. Après avoir approuvé l’appareil, revenez ici et DebridHub terminera la connexion automatiquement."),
            "reminders.day_count" to LocalizationEntry.Plural(
                one = "%{1} jour",
                other = "%{1} jours"
            ),
            "reminders.days_before_expiry" to LocalizationEntry.Text("Jours avant l’expiration"),
            "reminders.enable" to LocalizationEntry.Text("Activer les rappels"),
            "reminders.local_schedule_intro" to LocalizationEntry.Text("DebridHub programmera ces notifications locales sur cet appareil :"),
            "reminders.no_future_planned" to LocalizationEntry.Text("Aucun rappel futur n’est prévu pour le moment. Cela peut arriver si la date d’expiration est très proche, déjà passée ou si les fenêtres de rappel choisies sont déjà écoulées."),
            "reminders.notification.expired_yesterday" to LocalizationEntry.Text("Votre abonnement Real-Debrid a expiré hier"),
            "reminders.notification.expires_in" to LocalizationEntry.Plural(
                one = "Votre abonnement Real-Debrid expire dans %{1} jour",
                other = "Votre abonnement Real-Debrid expire dans %{1} jours"
            ),
            "reminders.notification.expires_today" to LocalizationEntry.Text("Votre abonnement Real-Debrid expire aujourd’hui"),
            "reminders.notifications_disabled" to LocalizationEntry.Text("Des rappels sont prévus, mais les notifications sont désactivées pour DebridHub. Réactivez-les dans les réglages du système si vous voulez recevoir ces alertes."),
            "reminders.notify_after_expiry" to LocalizationEntry.Text("Notifier après l’expiration"),
            "reminders.notify_on_expiry" to LocalizationEntry.Text("Notifier le jour de l’expiration"),
            "reminders.planned_times" to LocalizationEntry.Text("Heures de rappel prévues :"),
            "reminders.refresh_to_preview" to LocalizationEntry.Text("Actualisez votre compte pour prévisualiser les rappels locaux."),
            "reminders.schedule_title" to LocalizationEntry.Text("Planning prévisionnel des rappels"),
            "reminders.scheduled_item" to LocalizationEntry.Text("%{1} : %{2}"),
            "reminders.selected" to LocalizationEntry.Text("Sélectionné : %{1}"),
            "reminders.settings_title" to LocalizationEntry.Text("Réglages des rappels"),
            "reminders.turned_off" to LocalizationEntry.Text("Les rappels sont actuellement désactivés."),
            "trust_center.about_line_1" to LocalizationEntry.Text("Le périmètre actuel est volontairement restreint : authentification du compte, lecture du statut du compte, planification locale des rappels et export local des diagnostics."),
            "trust_center.about_line_2" to LocalizationEntry.Text("L’app n’implémente actuellement ni débridage, ni téléchargements, ni gestion de torrents, ni streaming, ni partage de liens générés, ni gestion multi-utilisateur."),
            "trust_center.about_line_3" to LocalizationEntry.Text("DebridHub utilise les endpoints officiels de l’API Real-Debrid et le flux d’authentification par appareil documenté. Les utilisateurs restent responsables du respect des Conditions et des règles de compte de Real-Debrid."),
            "trust_center.about_title" to LocalizationEntry.Text("À propos et conformité"),
            "trust_center.diagnostics_line_1" to LocalizationEntry.Text("L’export des diagnostics inclut actuellement la version de l’app, la version de l’OS, l’horodatage de la dernière synchronisation, l’état d’expiration du compte et quelques indicateurs d’exécution non sensibles."),
            "trust_center.diagnostics_line_2" to LocalizationEntry.Text("L’export des diagnostics exclut les jetons d’accès, les jetons de rafraîchissement, les secrets client, le nom d’utilisateur, l’adresse e-mail et l’historique complet du compte."),
            "trust_center.diagnostics_title" to LocalizationEntry.Text("Diagnostics"),
            "trust_center.hero_body" to LocalizationEntry.Text("Il s’agit d’un texte produit dans l’app basé sur l’implémentation actuelle, pas d’une couche marketing ni d’une vue web."),
            "trust_center.hero_title" to LocalizationEntry.Text("Voyez exactement comment DebridHub gère l’authentification, le stockage, les diagnostics et les limites fonctionnelles."),
            "trust_center.preview_unavailable" to LocalizationEntry.Text("L’aperçu des diagnostics n’est pas encore disponible."),
            "trust_center.privacy_line_1" to LocalizationEntry.Text("DebridHub n’a pas de backend. L’app communique directement avec Real-Debrid depuis votre appareil."),
            "trust_center.privacy_line_2" to LocalizationEntry.Text("Il n’y a ni SDK analytique, ni pixel de suivi, ni service de rapport de crash, ni synchronisation distante de compte dans l’app actuelle."),
            "trust_center.privacy_line_3" to LocalizationEntry.Text("Les notifications de rappel sont locales à cet appareil et sont planifiées à partir de l’état du compte stocké localement."),
            "trust_center.privacy_line_4" to LocalizationEntry.Text("L’export des diagnostics est manuel. Rien n’est envoyé nulle part, sauf si vous partagez explicitement le fichier exporté."),
            "trust_center.privacy_title" to LocalizationEntry.Text("Confidentialité"),
            "trust_center.security_line_1" to LocalizationEntry.Text("L’authentification utilise le flux officiel OAuth2 Device Flow de Real-Debrid plutôt qu’une collecte de mot de passe."),
            "trust_center.security_line_2_android" to LocalizationEntry.Text("Android stocke l’état d’authentification avec EncryptedSharedPreferences."),
            "trust_center.security_line_2_ios" to LocalizationEntry.Text("iOS stocke l’état d’authentification dans le Trousseau et migre l’ancien état NSUserDefaults lors de la première lecture."),
            "trust_center.security_line_3" to LocalizationEntry.Text("Se déconnecter efface l’état d’authentification enregistré et annule les rappels. DebridHub n’a pas besoin d’un serveur compagnon pour fonctionner."),
            "trust_center.security_title" to LocalizationEntry.Text("Sécurité")
        ),
        "de" to mapOf(
            "account.days_remaining" to LocalizationEntry.Text("Verbleibende Tage: %{1}"),
            "account.expires" to LocalizationEntry.Text("Läuft ab: %{1}"),
            "account.expiry_state.active" to LocalizationEntry.Text("Aktiv"),
            "account.expiry_state.expired" to LocalizationEntry.Text("Abgelaufen"),
            "account.expiry_state.expiring_soon" to LocalizationEntry.Text("Läuft bald ab"),
            "account.expiry_state.unknown" to LocalizationEntry.Text("Unbekannt"),
            "account.last_checked" to LocalizationEntry.Text("Zuletzt geprüft: %{1}"),
            "account.no_data" to LocalizationEntry.Text("Es wurden noch keine Kontodaten geladen."),
            "account.premium" to LocalizationEntry.Text("Premium: %{1}"),
            "account.section_title" to LocalizationEntry.Text("Kontostatus"),
            "account.state" to LocalizationEntry.Text("Status: %{1}"),
            "account.username" to LocalizationEntry.Text("Benutzername: %{1}"),
            "common.actions" to LocalizationEntry.Text("Aktionen"),
            "common.active" to LocalizationEntry.Text("Aktiv"),
            "common.app_name" to LocalizationEntry.Text("DebridHub"),
            "common.back" to LocalizationEntry.Text("Zurück"),
            "common.cancel_authorization" to LocalizationEntry.Text("Autorisierung abbrechen"),
            "common.connect_real_debrid" to LocalizationEntry.Text("Real-Debrid verbinden"),
            "common.copy_code" to LocalizationEntry.Text("Code kopieren"),
            "common.disconnect" to LocalizationEntry.Text("Trennen"),
            "common.enable_notifications" to LocalizationEntry.Text("Benachrichtigungen aktivieren"),
            "common.enabling_notifications" to LocalizationEntry.Text("Benachrichtigungen werden aktiviert..."),
            "common.export_json" to LocalizationEntry.Text("JSON exportieren"),
            "common.exporting" to LocalizationEntry.Text("Export läuft..."),
            "common.inactive" to LocalizationEntry.Text("Inaktiv"),
            "common.loading" to LocalizationEntry.Text("Lädt..."),
            "common.no_browser_available" to LocalizationEntry.Text("Kein Browser verfügbar, um Real-Debrid zu öffnen."),
            "common.none" to LocalizationEntry.Text("Keine"),
            "common.notifications" to LocalizationEntry.Text("Benachrichtigungen"),
            "common.open_authorization_page" to LocalizationEntry.Text("Autorisierungsseite öffnen"),
            "common.open_notification_settings" to LocalizationEntry.Text("Benachrichtigungseinstellungen öffnen"),
            "common.refresh_preview" to LocalizationEntry.Text("Vorschau aktualisieren"),
            "common.refresh_status" to LocalizationEntry.Text("Status aktualisieren"),
            "common.refreshing_status" to LocalizationEntry.Text("Aktualisieren..."),
            "common.share_diagnostics" to LocalizationEntry.Text("Diagnose teilen"),
            "common.start_again" to LocalizationEntry.Text("Erneut starten"),
            "common.starting" to LocalizationEntry.Text("Startet..."),
            "common.trust_center" to LocalizationEntry.Text("Vertrauenszentrum"),
            "common.unable_open_notification_settings" to LocalizationEntry.Text("Benachrichtigungseinstellungen konnten nicht geöffnet werden."),
            "common.unknown" to LocalizationEntry.Text("Unbekannt"),
            "errors.authorization_failed" to LocalizationEntry.Text("Die Autorisierung ist fehlgeschlagen."),
            "errors.network_unreachable" to LocalizationEntry.Text("Real-Debrid konnte nicht erreicht werden. Prüfe deine Internetverbindung oder versuche ein anderes Netzwerk."),
            "errors.secure_connection_failed" to LocalizationEntry.Text("Die sichere Verbindung zu Real-Debrid ist fehlgeschlagen. Dein Netzwerk scheint HTTPS-Verkehr zu api.real-debrid.com abzufangen oder herabzustufen. Deaktiviere Captive Portals, VPNs, Secure Web Gateways oder TLS-Inspektion oder versuche ein anderes Netzwerk."),
            "messages.authorization_completed" to LocalizationEntry.Text("Autorisierung abgeschlossen."),
            "messages.authorization_denied" to LocalizationEntry.Text("Real-Debrid hat die Autorisierungsanfrage abgelehnt."),
            "messages.authorization_expired" to LocalizationEntry.Text("Die Geräteautorisierung ist abgelaufen. Starte erneut."),
            "messages.authorization_unexpected" to LocalizationEntry.Text("Unerwarteter Autorisierungsstatus."),
            "messages.diagnostics_exported" to LocalizationEntry.Text("Diagnosen exportiert nach %{1}"),
            "messages.disconnected" to LocalizationEntry.Text("Von Real-Debrid getrennt."),
            "messages.notifications_enabled" to LocalizationEntry.Text("Benachrichtigungen aktiviert."),
            "messages.notifications_still_disabled" to LocalizationEntry.Text("Benachrichtigungen bleiben deaktiviert. Öffne die Systemeinstellungen, wenn du Erinnerungsalarme erhalten möchtest."),
            "messages.unable_export_diagnostics" to LocalizationEntry.Text("Diagnosen konnten nicht exportiert werden."),
            "messages.unable_load_diagnostics_preview" to LocalizationEntry.Text("Diagnosevorschau konnte nicht geladen werden."),
            "messages.unable_refresh_account" to LocalizationEntry.Text("Kontostatus konnte nicht aktualisiert werden."),
            "messages.unable_start_authorization" to LocalizationEntry.Text("Autorisierung konnte nicht gestartet werden."),
            "onboarding.before_connect_step_1" to LocalizationEntry.Text("1. Tippe auf Real-Debrid verbinden, um einen Gerätecode anzufordern."),
            "onboarding.before_connect_step_2" to LocalizationEntry.Text("2. Kopiere den Code bei Bedarf und bestätige das Gerät anschließend bei Real-Debrid."),
            "onboarding.before_connect_step_3" to LocalizationEntry.Text("3. Wenn die Browser-Weiterleitung unterbrochen wird, verwende unten Autorisierungsseite öffnen."),
            "onboarding.before_connect_step_4" to LocalizationEntry.Text("4. Kehre hierher zurück, während DebridHub auf die Bestätigung wartet."),
            "onboarding.before_connect_step_5" to LocalizationEntry.Text("Du kannst zuerst das Vertrauenszentrum öffnen, wenn du Datenschutz, Sicherheit, Diagnosen und Compliance-Details prüfen möchtest."),
            "onboarding.before_connect_title" to LocalizationEntry.Text("Bevor du verbindest"),
            "onboarding.direct_verification_url" to LocalizationEntry.Text("Direkte Bestätigungs-URL: %{1}"),
            "onboarding.enter_code" to LocalizationEntry.Text("Gib diesen Code bei Real-Debrid ein."),
            "onboarding.finish_authorization_title" to LocalizationEntry.Text("Autorisierung abschließen"),
            "onboarding.hero_body" to LocalizationEntry.Text("DebridHub kommuniziert direkt mit der offiziellen Real-Debrid-API. Tokens bleiben auf dem Gerät und es wird kein Backend verwendet."),
            "onboarding.hero_title" to LocalizationEntry.Text("Behalte dein Real-Debrid-Abonnement im Blick und verlängere es, bevor es abläuft."),
            "onboarding.notifications_already_enabled" to LocalizationEntry.Text("Benachrichtigungen sind auf diesem Gerät bereits aktiviert."),
            "onboarding.notifications_disabled_help" to LocalizationEntry.Text("Benachrichtigungen sind für DebridHub derzeit deaktiviert. Du kannst die Berechtigungsanfrage erneut versuchen oder die Alarme in den Systemeinstellungen wieder aktivieren."),
            "onboarding.notifications_later" to LocalizationEntry.Text("Du kannst Benachrichtigungen jetzt oder später aktivieren. Erinnerungsalarme beginnen, sobald dein Konto verbunden ist."),
            "onboarding.polling_until" to LocalizationEntry.Text("Prüfung alle %{1}s bis %{2}"),
            "onboarding.verification_url" to LocalizationEntry.Text("Bestätigungs-URL: %{1}"),
            "onboarding.waiting_for_approval" to LocalizationEntry.Text("Warte auf die Bestätigung von Real-Debrid. Nachdem du das Gerät bestätigt hast, kehre hierher zurück und DebridHub schließt die Anmeldung automatisch ab."),
            "reminders.day_count" to LocalizationEntry.Plural(
                one = "%{1} Tag",
                other = "%{1} Tage"
            ),
            "reminders.days_before_expiry" to LocalizationEntry.Text("Tage vor Ablauf"),
            "reminders.enable" to LocalizationEntry.Text("Erinnerungen aktivieren"),
            "reminders.local_schedule_intro" to LocalizationEntry.Text("DebridHub wird diese lokalen Benachrichtigungen auf diesem Gerät planen:"),
            "reminders.no_future_planned" to LocalizationEntry.Text("Derzeit sind keine zukünftigen Erinnerungen geplant. Das kann passieren, wenn das Ablaufdatum sehr nah ist, bereits vorbei ist oder deine gewählten Erinnerungsfenster bereits in der Vergangenheit liegen."),
            "reminders.notification.expired_yesterday" to LocalizationEntry.Text("Dein Real-Debrid-Abonnement ist gestern abgelaufen"),
            "reminders.notification.expires_in" to LocalizationEntry.Plural(
                one = "Dein Real-Debrid-Abonnement läuft in %{1} Tag ab",
                other = "Dein Real-Debrid-Abonnement läuft in %{1} Tagen ab"
            ),
            "reminders.notification.expires_today" to LocalizationEntry.Text("Dein Real-Debrid-Abonnement läuft heute ab"),
            "reminders.notifications_disabled" to LocalizationEntry.Text("Erinnerungen sind geplant, aber Benachrichtigungen sind für DebridHub deaktiviert. Aktiviere sie in den Systemeinstellungen wieder, wenn du diese Hinweise erhalten möchtest."),
            "reminders.notify_after_expiry" to LocalizationEntry.Text("Nach Ablauf benachrichtigen"),
            "reminders.notify_on_expiry" to LocalizationEntry.Text("Am Ablaufdatum benachrichtigen"),
            "reminders.planned_times" to LocalizationEntry.Text("Geplante Erinnerungszeiten:"),
            "reminders.refresh_to_preview" to LocalizationEntry.Text("Aktualisiere dein Konto, um lokale Erinnerungen in der Vorschau zu sehen."),
            "reminders.schedule_title" to LocalizationEntry.Text("Erwarteter Erinnerungsplan"),
            "reminders.scheduled_item" to LocalizationEntry.Text("%{1}: %{2}"),
            "reminders.selected" to LocalizationEntry.Text("Ausgewählt: %{1}"),
            "reminders.settings_title" to LocalizationEntry.Text("Erinnerungseinstellungen"),
            "reminders.turned_off" to LocalizationEntry.Text("Erinnerungen sind derzeit deaktiviert."),
            "trust_center.about_line_1" to LocalizationEntry.Text("Der aktuelle Umfang ist absichtlich eng gefasst: Kontoauthentifizierung, Abrufe des Kontostatus, lokale Erinnerungsplanung und lokaler Diagnoseexport."),
            "trust_center.about_line_2" to LocalizationEntry.Text("Die App implementiert derzeit weder Unrestrict, Downloads, Torrent-Verwaltung, Streaming, das Teilen generierter Links noch Multi-User-Kontoverwaltung."),
            "trust_center.about_line_3" to LocalizationEntry.Text("DebridHub verwendet offizielle Real-Debrid-API-Endpunkte und den dokumentierten Device-Auth-Flow. Nutzer bleiben selbst dafür verantwortlich, die Real-Debrid-Bedingungen und Kontoregeln einzuhalten."),
            "trust_center.about_title" to LocalizationEntry.Text("Überblick & Compliance"),
            "trust_center.diagnostics_line_1" to LocalizationEntry.Text("Der Diagnoseexport enthält derzeit die App-Version, die OS-Version, den Zeitstempel der letzten Synchronisierung, den Ablaufstatus des Kontos und begrenzte nicht sensible Laufzeitflags."),
            "trust_center.diagnostics_line_2" to LocalizationEntry.Text("Der Diagnoseexport schließt Zugriffstokens, Refresh-Tokens, Client-Secrets, Benutzernamen, E-Mail-Adresse und den vollständigen Kontoverlauf aus."),
            "trust_center.diagnostics_title" to LocalizationEntry.Text("Diagnosen"),
            "trust_center.hero_body" to LocalizationEntry.Text("Dies ist In-App-Produkttext basierend auf der aktuellen Implementierung, keine Marketing-Schicht und keine Webansicht."),
            "trust_center.hero_title" to LocalizationEntry.Text("Sieh dir genau an, wie DebridHub Authentifizierung, Speicherung, Diagnosen und Funktionsgrenzen handhabt."),
            "trust_center.preview_unavailable" to LocalizationEntry.Text("Die Diagnosevorschau ist noch nicht verfügbar."),
            "trust_center.privacy_line_1" to LocalizationEntry.Text("DebridHub hat kein Backend. Die App spricht direkt von deinem Gerät mit Real-Debrid."),
            "trust_center.privacy_line_2" to LocalizationEntry.Text("Es gibt in der aktuellen App kein Analyse-SDK, kein Tracking-Pixel, keinen Crash-Reporting-Dienst und keine Kontosynchronisierung über einen Server."),
            "trust_center.privacy_line_3" to LocalizationEntry.Text("Erinnerungsbenachrichtigungen sind lokal auf diesem Gerät und werden anhand des lokal gespeicherten Kontostatus geplant."),
            "trust_center.privacy_line_4" to LocalizationEntry.Text("Der Diagnoseexport ist manuell. Es wird nichts irgendwohin gesendet, es sei denn, du teilst die exportierte Datei ausdrücklich selbst."),
            "trust_center.privacy_title" to LocalizationEntry.Text("Datenschutz"),
            "trust_center.security_line_1" to LocalizationEntry.Text("Die Authentifizierung verwendet den offiziellen OAuth2-Device-Flow von Real-Debrid statt einer Passworteingabe."),
            "trust_center.security_line_2_android" to LocalizationEntry.Text("Android speichert den Authentifizierungsstatus mit EncryptedSharedPreferences."),
            "trust_center.security_line_2_ios" to LocalizationEntry.Text("iOS speichert den Authentifizierungsstatus im Schlüsselbund und migriert beim ersten Lesen den alten NSUserDefaults-Status."),
            "trust_center.security_line_3" to LocalizationEntry.Text("Beim Trennen werden gespeicherter Authentifizierungsstatus gelöscht und Erinnerungen abgebrochen. DebridHub benötigt keinen Begleitserver, um zu funktionieren."),
            "trust_center.security_title" to LocalizationEntry.Text("Sicherheit")
        ),
        "tr" to mapOf(
            "account.days_remaining" to LocalizationEntry.Text("Kalan gün: %{1}"),
            "account.expires" to LocalizationEntry.Text("Bitiş: %{1}"),
            "account.expiry_state.active" to LocalizationEntry.Text("Aktif"),
            "account.expiry_state.expired" to LocalizationEntry.Text("Süresi doldu"),
            "account.expiry_state.expiring_soon" to LocalizationEntry.Text("Yakında bitiyor"),
            "account.expiry_state.unknown" to LocalizationEntry.Text("Bilinmiyor"),
            "account.last_checked" to LocalizationEntry.Text("Son kontrol: %{1}"),
            "account.no_data" to LocalizationEntry.Text("Henüz hesap verisi yüklenmedi."),
            "account.premium" to LocalizationEntry.Text("Premium: %{1}"),
            "account.section_title" to LocalizationEntry.Text("Hesap Durumu"),
            "account.state" to LocalizationEntry.Text("Durum: %{1}"),
            "account.username" to LocalizationEntry.Text("Kullanıcı adı: %{1}"),
            "common.actions" to LocalizationEntry.Text("İşlemler"),
            "common.active" to LocalizationEntry.Text("Aktif"),
            "common.app_name" to LocalizationEntry.Text("DebridHub"),
            "common.back" to LocalizationEntry.Text("Geri"),
            "common.cancel_authorization" to LocalizationEntry.Text("Yetkilendirmeyi iptal et"),
            "common.connect_real_debrid" to LocalizationEntry.Text("Real-Debrid bağla"),
            "common.copy_code" to LocalizationEntry.Text("Kodu kopyala"),
            "common.disconnect" to LocalizationEntry.Text("Bağlantıyı kes"),
            "common.enable_notifications" to LocalizationEntry.Text("Bildirimleri aç"),
            "common.enabling_notifications" to LocalizationEntry.Text("Bildirimler açılıyor..."),
            "common.export_json" to LocalizationEntry.Text("JSON dışa aktar"),
            "common.exporting" to LocalizationEntry.Text("Dışa aktarılıyor..."),
            "common.inactive" to LocalizationEntry.Text("Pasif"),
            "common.loading" to LocalizationEntry.Text("Yükleniyor..."),
            "common.no_browser_available" to LocalizationEntry.Text("Real-Debrid’i açmak için kullanılabilir tarayıcı yok."),
            "common.none" to LocalizationEntry.Text("Yok"),
            "common.notifications" to LocalizationEntry.Text("Bildirimler"),
            "common.open_authorization_page" to LocalizationEntry.Text("Yetkilendirme sayfasını aç"),
            "common.open_notification_settings" to LocalizationEntry.Text("Bildirim ayarlarını aç"),
            "common.refresh_preview" to LocalizationEntry.Text("Önizlemeyi yenile"),
            "common.refresh_status" to LocalizationEntry.Text("Durumu yenile"),
            "common.refreshing_status" to LocalizationEntry.Text("Yenileniyor..."),
            "common.share_diagnostics" to LocalizationEntry.Text("Tanıyı paylaş"),
            "common.start_again" to LocalizationEntry.Text("Baştan başla"),
            "common.starting" to LocalizationEntry.Text("Başlatılıyor..."),
            "common.trust_center" to LocalizationEntry.Text("Güven Merkezi"),
            "common.unable_open_notification_settings" to LocalizationEntry.Text("Bildirim ayarları açılamadı."),
            "common.unknown" to LocalizationEntry.Text("Bilinmiyor"),
            "errors.authorization_failed" to LocalizationEntry.Text("Yetkilendirme başarısız oldu."),
            "errors.network_unreachable" to LocalizationEntry.Text("Real-Debrid’e ulaşılamadı. İnternet bağlantını kontrol et veya başka bir ağ dene."),
            "errors.secure_connection_failed" to LocalizationEntry.Text("Real-Debrid ile güvenli bağlantı başarısız oldu. Ağın, api.real-debrid.com adresine giden HTTPS trafiğini kesiyor ya da düşürüyor gibi görünüyor. Captive portal, VPN, güvenli web ağ geçidi veya TLS incelemesini kapat ya da başka bir ağ dene."),
            "messages.authorization_completed" to LocalizationEntry.Text("Yetkilendirme tamamlandı."),
            "messages.authorization_denied" to LocalizationEntry.Text("Real-Debrid yetkilendirme isteğini reddetti."),
            "messages.authorization_expired" to LocalizationEntry.Text("Cihaz yetkilendirme oturumu sona erdi. Baştan başla."),
            "messages.authorization_unexpected" to LocalizationEntry.Text("Beklenmeyen yetkilendirme durumu."),
            "messages.diagnostics_exported" to LocalizationEntry.Text("Tanılar şuraya dışa aktarıldı: %{1}"),
            "messages.disconnected" to LocalizationEntry.Text("Real-Debrid bağlantısı kesildi."),
            "messages.notifications_enabled" to LocalizationEntry.Text("Bildirimler açıldı."),
            "messages.notifications_still_disabled" to LocalizationEntry.Text("Bildirimler kapalı kaldı. Hatırlatma uyarıları istiyorsan sistem ayarlarını aç."),
            "messages.unable_export_diagnostics" to LocalizationEntry.Text("Tanılar dışa aktarılamadı."),
            "messages.unable_load_diagnostics_preview" to LocalizationEntry.Text("Tanı önizlemesi yüklenemedi."),
            "messages.unable_refresh_account" to LocalizationEntry.Text("Hesap durumu yenilenemedi."),
            "messages.unable_start_authorization" to LocalizationEntry.Text("Yetkilendirme başlatılamadı."),
            "onboarding.before_connect_step_1" to LocalizationEntry.Text("1. Bir cihaz kodu istemek için Real-Debrid bağla düğmesine dokun."),
            "onboarding.before_connect_step_2" to LocalizationEntry.Text("2. İstersen kodu kopyala, sonra cihazı Real-Debrid üzerinde onayla."),
            "onboarding.before_connect_step_3" to LocalizationEntry.Text("3. Tarayıcı yönlendirmesi kesilirse aşağıdaki Yetkilendirme sayfasını aç seçeneğini kullan."),
            "onboarding.before_connect_step_4" to LocalizationEntry.Text("4. DebridHub tamamlanmayı beklerken buraya geri dön."),
            "onboarding.before_connect_step_5" to LocalizationEntry.Text("Gizlilik, güvenlik, tanı ve uyumluluk ayrıntılarını incelemek istersen önce Güven Merkezi’ni açabilirsin."),
            "onboarding.before_connect_title" to LocalizationEntry.Text("Bağlanmadan önce"),
            "onboarding.direct_verification_url" to LocalizationEntry.Text("Doğrudan doğrulama URL’si: %{1}"),
            "onboarding.enter_code" to LocalizationEntry.Text("Bu kodu Real-Debrid üzerinde gir."),
            "onboarding.finish_authorization_title" to LocalizationEntry.Text("Yetkilendirmeyi tamamla"),
            "onboarding.hero_body" to LocalizationEntry.Text("DebridHub doğrudan resmi Real-Debrid API’siyle konuşur. Token’lar cihazda kalır ve hiçbir backend kullanılmaz."),
            "onboarding.hero_title" to LocalizationEntry.Text("Real-Debrid aboneliğini takip et ve süresi dolmadan yenile."),
            "onboarding.notifications_already_enabled" to LocalizationEntry.Text("Bu cihazda bildirimler zaten açık."),
            "onboarding.notifications_disabled_help" to LocalizationEntry.Text("DebridHub için bildirimler şu anda kapalı. İzin istemeyi tekrar deneyebilir veya sistem ayarlarından uyarıları yeniden açabilirsin."),
            "onboarding.notifications_later" to LocalizationEntry.Text("Bildirimleri şimdi ya da sonra açabilirsin. Hesabın bağlandıktan sonra hatırlatma uyarıları başlayacak."),
            "onboarding.polling_until" to LocalizationEntry.Text("%{1} sn aralıkla %{2} anına kadar kontrol ediliyor"),
            "onboarding.verification_url" to LocalizationEntry.Text("Doğrulama URL’si: %{1}"),
            "onboarding.waiting_for_approval" to LocalizationEntry.Text("Real-Debrid onayı bekleniyor. Cihazı onayladıktan sonra buraya dön; DebridHub giriş işlemini otomatik olarak tamamlayacak."),
            "reminders.day_count" to LocalizationEntry.Plural(
                one = "%{1} gün",
                other = "%{1} gün"
            ),
            "reminders.days_before_expiry" to LocalizationEntry.Text("Bitişten önceki günler"),
            "reminders.enable" to LocalizationEntry.Text("Hatırlatmaları aç"),
            "reminders.local_schedule_intro" to LocalizationEntry.Text("DebridHub bu yerel bildirimleri bu cihazda planlayacak:"),
            "reminders.no_future_planned" to LocalizationEntry.Text("Şu anda planlanmış gelecekteki hatırlatma yok. Bu, bitiş tarihi çok yakınsa, geçmişse veya seçtiğin hatırlatma aralıkları geride kaldıysa olabilir."),
            "reminders.notification.expired_yesterday" to LocalizationEntry.Text("Real-Debrid aboneliğinin süresi dün doldu"),
            "reminders.notification.expires_in" to LocalizationEntry.Plural(
                one = "Real-Debrid aboneliğin %{1} gün içinde sona erecek",
                other = "Real-Debrid aboneliğin %{1} gün içinde sona erecek"
            ),
            "reminders.notification.expires_today" to LocalizationEntry.Text("Real-Debrid aboneliğin bugün sona eriyor"),
            "reminders.notifications_disabled" to LocalizationEntry.Text("Hatırlatmalar planlandı ancak DebridHub için bildirimler kapalı. Bu uyarıların gelmesini istiyorsan sistem ayarlarından yeniden aç."),
            "reminders.notify_after_expiry" to LocalizationEntry.Text("Bitişten sonra bildir"),
            "reminders.notify_on_expiry" to LocalizationEntry.Text("Bitiş gününde bildir"),
            "reminders.planned_times" to LocalizationEntry.Text("Planlanan hatırlatma zamanları:"),
            "reminders.refresh_to_preview" to LocalizationEntry.Text("Yerel hatırlatmaları önizlemek için hesabını yenile."),
            "reminders.schedule_title" to LocalizationEntry.Text("Beklenen Hatırlatma Takvimi"),
            "reminders.scheduled_item" to LocalizationEntry.Text("%{1}: %{2}"),
            "reminders.selected" to LocalizationEntry.Text("Seçili: %{1}"),
            "reminders.settings_title" to LocalizationEntry.Text("Hatırlatma Ayarları"),
            "reminders.turned_off" to LocalizationEntry.Text("Hatırlatmalar şu anda kapalı."),
            "trust_center.about_line_1" to LocalizationEntry.Text("Mevcut kapsam kasıtlı olarak dardır: hesap kimlik doğrulama, hesap durumu okuma, yerel hatırlatma planlama ve yerel tanı dışa aktarımı."),
            "trust_center.about_line_2" to LocalizationEntry.Text("Uygulama şu anda unrestrict, indirme, torrent yönetimi, akış, üretilen bağlantı paylaşımı veya çok kullanıcılı hesap yönetimi uygulamaz."),
            "trust_center.about_line_3" to LocalizationEntry.Text("DebridHub resmi Real-Debrid API uç noktalarını ve belgelenmiş cihaz kimlik doğrulama akışını kullanır. Kullanıcılar yine de Real-Debrid’in kendi Koşullarına ve hesap kurallarına uymaktan sorumludur."),
            "trust_center.about_title" to LocalizationEntry.Text("Hakkında ve Uyumluluk"),
            "trust_center.diagnostics_line_1" to LocalizationEntry.Text("Tanı dışa aktarımı şu anda uygulama sürümünü, işletim sistemi sürümünü, son eşitleme zamanını, hesap bitiş durumunu ve sınırlı sayıda hassas olmayan çalışma bilgisini içerir."),
            "trust_center.diagnostics_line_2" to LocalizationEntry.Text("Tanı dışa aktarımı erişim token’larını, yenileme token’larını, istemci sırlarını, kullanıcı adını, e-posta adresini ve tam hesap geçmişini içermez."),
            "trust_center.diagnostics_title" to LocalizationEntry.Text("Tanılar"),
            "trust_center.hero_body" to LocalizationEntry.Text("Bu, mevcut uygulamaya dayanan uygulama içi ürün metnidir; pazarlama katmanı ya da web görünümü değildir."),
            "trust_center.hero_title" to LocalizationEntry.Text("DebridHub’ın kimlik doğrulama, depolama, tanı ve özellik sınırlarını nasıl ele aldığını tam olarak gör."),
            "trust_center.preview_unavailable" to LocalizationEntry.Text("Tanı önizlemesi henüz kullanılamıyor."),
            "trust_center.privacy_line_1" to LocalizationEntry.Text("DebridHub’ın backend’i yoktur. Uygulama cihazından doğrudan Real-Debrid ile konuşur."),
            "trust_center.privacy_line_2" to LocalizationEntry.Text("Mevcut uygulamada analitik SDK’sı, takip pikseli, çökme raporlama servisi ya da uzak hesap eşitleme yoktur."),
            "trust_center.privacy_line_3" to LocalizationEntry.Text("Hatırlatma bildirimleri bu cihaza özeldir ve yerel olarak depolanan hesap durumuna göre planlanır."),
            "trust_center.privacy_line_4" to LocalizationEntry.Text("Tanı dışa aktarımı manueldir. Dışa aktarılan dosyayı açıkça paylaşmadığın sürece hiçbir yere gönderilmez."),
            "trust_center.privacy_title" to LocalizationEntry.Text("Gizlilik"),
            "trust_center.security_line_1" to LocalizationEntry.Text("Kimlik doğrulama, parola toplamaktansa Real-Debrid’in resmi OAuth2 cihaz akışını kullanır."),
            "trust_center.security_line_2_android" to LocalizationEntry.Text("Android, kimlik doğrulama durumunu EncryptedSharedPreferences ile saklar."),
            "trust_center.security_line_2_ios" to LocalizationEntry.Text("iOS, kimlik doğrulama durumunu Keychain’de saklar ve ilk okumada eski NSUserDefaults verisini taşır."),
            "trust_center.security_line_3" to LocalizationEntry.Text("Bağlantıyı kesmek kayıtlı kimlik doğrulama durumunu temizler ve hatırlatmaları iptal eder. DebridHub’ın çalışması için yardımcı bir sunucu gerekmez."),
            "trust_center.security_title" to LocalizationEntry.Text("Güvenlik")
        )
    )
}
